/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorSummaryRouteImport } from './routes/supervisor.summary'
import { Route as SupervisorDashboardRouteImport } from './routes/supervisor.dashboard'
import { Route as StaffQueueRouteImport } from './routes/staff.queue'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenBookRouteImport } from './routes/citizen.book'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorSummaryRoute = SupervisorSummaryRouteImport.update({
  id: '/supervisor/summary',
  path: '/supervisor/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorDashboardRoute = SupervisorDashboardRouteImport.update({
  id: '/supervisor/dashboard',
  path: '/supervisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/staff/queue',
  path: '/staff/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen/dashboard',
  path: '/citizen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenBookRoute = CitizenBookRouteImport.update({
  id: '/citizen/book',
  path: '/citizen/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/book': typeof CitizenBookRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/summary': typeof SupervisorSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/book': typeof CitizenBookRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/summary': typeof SupervisorSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/book': typeof CitizenBookRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/staff/queue': typeof StaffQueueRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/summary': typeof SupervisorSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/citizen/book'
    | '/citizen/dashboard'
    | '/staff/queue'
    | '/supervisor/dashboard'
    | '/supervisor/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/citizen/book'
    | '/citizen/dashboard'
    | '/staff/queue'
    | '/supervisor/dashboard'
    | '/supervisor/summary'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/citizen/book'
    | '/citizen/dashboard'
    | '/staff/queue'
    | '/supervisor/dashboard'
    | '/supervisor/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CitizenBookRoute: typeof CitizenBookRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  StaffQueueRoute: typeof StaffQueueRoute
  SupervisorDashboardRoute: typeof SupervisorDashboardRoute
  SupervisorSummaryRoute: typeof SupervisorSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/summary': {
      id: '/supervisor/summary'
      path: '/supervisor/summary'
      fullPath: '/supervisor/summary'
      preLoaderRoute: typeof SupervisorSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/dashboard': {
      id: '/supervisor/dashboard'
      path: '/supervisor/dashboard'
      fullPath: '/supervisor/dashboard'
      preLoaderRoute: typeof SupervisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/staff/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/book': {
      id: '/citizen/book'
      path: '/citizen/book'
      fullPath: '/citizen/book'
      preLoaderRoute: typeof CitizenBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CitizenBookRoute: CitizenBookRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  StaffQueueRoute: StaffQueueRoute,
  SupervisorDashboardRoute: SupervisorDashboardRoute,
  SupervisorSummaryRoute: SupervisorSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
